export const GET_STATUSINFO = 'GET_STATUSINFO';
export const GET_STATUSINFO_ERROR = 'GET_STATUSINFO_ERROR';
export const GET_STATUSINFO_SUCCESS = 'GET_STATUSINFO_SUCCESS';

export const GET_SERVICES = 'GET_SERVICES';
export const GET_SERVICES_ERROR = 'GET_SERVICES_ERROR';
export const GET_SERVICES_SUCCESS = 'GET_SERVICES_SUCCESS';
